name: Run Shell Script to build in all platforms

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run shell script
        run: |
          chmod +x ./build_multiplatform.sh
          ./build_multiplatform.sh